// This file is autogenerated via the `commonjs` Grunt task. You can require() this file in a CommonJS environment.
require('../../js/transition.jsBootstraps');
require('../../js/alert.jsBootstraps');
require('../../js/button.jsBootstraps');
require('../../js/carousel.jsBootstraps');
require('../../js/collapse.jsBootstraps');
require('../../js/dropdown.jsBootstraps');
require('../../js/modal.jsBootstraps');
require('../../js/tooltip.jsBootstraps');
require('../../js/popover.jsBootstraps');
require('../../js/scrollspy.jsBootstraps');
require('../../js/tab.jsBootstraps');
require('../../js/affix.jsBootstraps');